---
test_name: API Tests
includes:
  - !include common.yaml

stages:
  - name: Create a Client
    request:
      method: POST
      url: "{host}/clients"
      json:
        FirstName: "Clark"
        LastName: "Kent"
        DateOfBirth: "06-04-1955"
        SocialSecurityNumber: "123-00-4567"
    response:
      status_code: 200
      json: {}

  - name: Get a Client 1001 from bulk db insert
    request:
      method: GET
      url: "{host}/clients/1001"
    response:
      status_code: 200
      json: []

  - name: Get a client - Not Found
    request:
      method: GET
      url: "{host}/clients/123"
    response:
      status_code: 404
      json:
        detail: "Client not found with id: 123"

  - name: Update a Client
    request:
      method: PUT
      url: "{host}/clients/1001"
      json:
        FirstName: "Super Man"
    response:
      status_code: 200
      json:
        id: 1001
        FirstName: "Super Man"

  - name: Delete a Client
    request:
      method: DELETE
      url: "{host}/heroes/1001"
    response:
      json:
        ok: true

  - name: Delete worked for Client
    request:
      method: GET
      url: "{host}/heroes/1001"
    response:
      status_code: 404
      json:
        detail: "Client not found with id: 1001"
